### ISSUE TITLE
Determine the process for pulling in a slate dependency

### ISSUE THREAD

**Issue by bmds** [cartridge/cartridge-cli#2]
As we are going to split out the sections of slate so that we can pull in only the parts that we need then we need to think about how we will manage that process.

The initial thinking is that each project will have a copy of .slaterc in the root listing the slate modules that it is using along with when it was created.

Each slate module has it's own package.json file containing only the dependencies that it has which are merged together to create the project package.json file. Potentially using [package-merge](https://www.npmjs.com/package/package-merge).

Each slate module would need to do some or all of the following:
* Add it's dependencies to the project package.json
* Add it's task file to the project **gulpTasks** directory
* Add files needed for the task to the project directory
* Modify the main config object
* Specify task names it introduces so that they can be included in the default task

Slate would remain the minimal gulp setup that could be used on any project with the rest of the project being split out to seperate repositorys such as **slate-localserver**, **slate-responsive-images** etc.

We need to discuss how we pull these repositories in and merge the contents to build a slate setup specific to the project requirements.

**Comment by tawashley** [comment]
One option could be to make the config file (to replace .slaterc or a second one) which is a JS file. This would run first before anything else. (similar to Grunt's config object, or Karma `karma.conf.js` file).

**Comment by bmds** [comment]
As an initial thought could the modules be checked out in to a **.slate** directory within the project that contains the checked out modules.

All of this is feeling very much like npm. There must be a way that we can leverage npm to do the work for us with this.

**Comment by tawashley** [comment]
This does bring in the other discussion of monorepo (everything in one place) versus having everything/most things split out. https://github.com/emberjs/ember.js/tree/master/packages - Ember has all of their modules in the main repo.

**Comment by bmds** [comment]
Thinking about this over lunch, we don't have to complicate this at all we could use the following as a workflow:

The base slate setup remains as it is, ``slate init`` copies the files from the latest tagged release and adds them to the current working directory.

Each component is a fully fledged npm package, with a main file that resolves adding the component to an existing project. Adding them to a project via ``slate init`` or ``slate add`` uses the following approach:

- Quarry runs ``npm i --save slate-component`` for the specific component
- After install is finished quarry requires the component
- Quarry then calls init() on the required component.
- Init then adds the required files to the current working directory

This gives us the following benefits:

- We use npm for managing pages so that we're not reinventing the wheel.
- The project package.json stays relatively sane as the dependencies for a particular component live within it's package.json. While the project one contains the base dependencies and "slate-local-server": "^1.0.0" for example.
- We use npm for managing updates simply wrapping it with quarry to manage the pre /post install functions

If we feel that there will be too much duplication with the ``component.init()`` methods then we can pull those out to quarry which calls multiple methods such as ``component.getTaskFile()``, ``component.getConfig()`` etc.


Thoughts?

**Comment by bmds** [comment]
It's also worth noting that this should make upgrading a component easier too.

The other potential is that the task files themselves are never moved. The post install script simply manages modifying the project config and adding the location of the task file to an array that quarry manages for the project.

Then the default gulp file loops through that array and calls them as it does at present.

With that solution we trade a bit of transparency with how the tasks work along for ease of maintenance / upgrade ability.

It would also make customising the files for testing new features harder, unless in that instance we explicitly bring the files within the project as you would no longer be using the specific component at that point.

**Comment by bmds** [comment]
The other question is should each project start as a fork of slate with all the attendant history or should it be a simple download of the files along with running ``git init``.

Slate could be simplified down to the point where it is the main gulpfile & all of the config. Everything else gets pulled out in to a component, however the Sass and JS modules are simply default ones. That way everything is upgradeable & the base file is unlikely to need changing

**Comment by tawashley** [comment]
Using npm as the 'source' of any modules, components I think is something we should do for sure. 

@bmds 
Regarding your point of managing them, the lifecycle boiled down would then be...

* Grab `slate-component` from npm
* Run some setup code inside of it, mentioned as the `init()` setup
* Copy over relevant files into the current working directory

After the initial `slate init` (if that's what it's going to be called :smile:) has finished you would be all setup. To this end, I'm unsure if the `--save` npm flag would be needed, as the `slate-component` code would only be used once, during the install? After that, the files would be added as part of the repo and that's that.

The comment regarding how to manage initialising a git repo could be done programatically. If the `.git` folder isn't found in the current working directory then it would ask `Do you want this directory to be initialised as a git repo` or something. If the `.git` folder is found then nothing would be done.

**Comment by tawashley** [comment]
The approach of cloning into `quarry` the `slate` project before project generation has a few downsides. Mainly the potential loss of having a slate version number (if a fresh clone is done each time quarry generates a project) or if the versioning is done through tagging, the additional management of getting a tagged release of `slate` into `quarry`.

Instead, should `quarry` assume that `slate` is already installed on the local machine.

So...

`npm install -g slate` would install slate
`npm install -g quarry` would install quarry

quarry would check if slate is installed and if so, go ahead with things. If slate is not installed then error and exit. 

`slate` and `quarry` should be maintained seperately and to whenever possible allow for changes to be made without adversely affecting each other.

This approach would be akin to how `grunt` and `grunt-cli` are seperate tools but the latter requires the former to work.

**Comment by bmds** [comment]
Resolved using npm modules
